[tools]
python = "3.11"

[tasks.setup-dev]
description = "Setup development environment"
run = [
    "rustup toolchain install nightly --component rust-src",
    "rustup target add riscv32imac-unknown-none-elf",
    "rustup update",
    "cargo install espup ldproxy cargo-espflash",
    "espup install",
]
